### ISSUE TITLE
MakeAddressable no longer defined after update to raw

### ISSUE THREAD

**Issue by mikaelberg** [feyeleanor/slices#2]
feyeleanor/slices needs update to conform to https://github.com/feyeleanor/raw/commit/6e1bed04d4993417da963db9d7baaace5b7f4138.

Patch below:
```From fcc9d2b1e97cd378cbea30b0f5c9034e416f2d09 Mon Sep 17 00:00:00 2001
From: Mikael Berg <m@mikaelberg.se>
Date: Tue, 27 Dec 2016 15:31:51 +0100
Subject: [PATCH] Replace call to deprecated raw.MakeAddressable

---
 reflected.go | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/reflected.go b/reflected.go
index 4c219e2..cce4619 100644
--- a/reflected.go
+++ b/reflected.go
@@ -42,8 +42,12 @@ func (s RSlice) MakeSlice(length, capacity int) (r RSlice) {
 }
 
 func (s *RSlice) MakeAddressable() {
-	n := raw.MakeAddressable(*s.Value)
-	s.Value = &n
+	n := raw.Duplicate(*s.Value)
+	if value, ok := n.(reflect.Value); ok {
+		s.Value = &value
+	} else {
+		s.Value = nil
+	}
 }
 
 func (s *RSlice) setValue(v reflect.Value) {
-- 
2.9.2.windows.1

```
[0001-Replace-call-to-deprecated-raw.MakeAddressable.zip](https://github.com/feyeleanor/slices/files/674260/0001-Replace-call-to-deprecated-raw.MakeAddressable.zip)

**Comment by mikaelberg** [comment]
This issue affects https://github.com/goamz/goamz/blob/master/cloudwatch/cloudwatch.go

**Comment by feyeleanor** [comment]
Sorry for the slow response - enjoying a little too much Xmas cheer :)

I'll update the code now.

**Comment by feyeleanor** [comment]
I've reinstated MakeAddressable in RAW with slightly different semantics and made an appropriate change here. All tests pass so hopefully this will serve your purposes.
